PACKAGE_NAME="t2_trackpad_actuator"
PACKAGE_VERSION="0.01"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build KVER=${kernelver}"

BUILT_MODULE_NAME[0]="t2_trackpad_actuator"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
